In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import os
import sys
sys.path.append(os.path.abspath("..")) 



df = pd.read_csv("../data/raw/osm_69_2025.csv", sep=',')

In [ ]:
# Vérifications
display(df)
print("\n",df.info())
print("total_rows:",df.shape[0],"total_columns:",df.shape[1])
print("\n",df.isna().sum())
print("\n","Duplicated Any:", df.duplicated().sum(),"\n")
print(df.info())

df.describe()

,@id,@type,@lat,@lon,@timestamp,name,amenity,shop,healthcare,sport,...,natural,addr:housenumber,addr:street,addr:postcode,addr:city,operator,brand,phone,website,opening_hours
0,10703312,node,45.721028,5.075846,2025-12-02T15:47:02Z,Lyon-Saint-Exupéry TGV,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,13801872,node,45.592430,4.785264,2021-11-11T18:00:52Z,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,15505498,node,45.599651,4.570600,2024-04-13T21:31:21Z,Sainte-Catherine - Le Bourg,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,15505707,node,45.585721,4.634773,2024-04-13T20:11:37Z,La Roche,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,15505751,node,45.604146,4.688669,2024-04-11T21:48:11Z,Pont Rompu,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50414,21406131,relation,45.667361,4.515162,2026-09-17T13:51:12Z,Duerne - Le Layat,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50415,21406132,relation,45.640724,4.521767,2026-09-17T13:51:12Z,La Chèvre,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50416,21406133,relation,45.635327,4.460479,2026-09-17T13:51:12Z,Les Rameaux,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50417,21406134,relation,45.631533,4.429948,2026-09-17T13:51:12Z,ZI Grange Eglise,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50418,21420076,relation,45.868489,4.669699,2026-09-20T16:24:53Z,Belmont d'Azergues - Place de la Mairie,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50419 entries, 0 to 50418
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   @id               50419 non-null  int64
 1   @type             50419 non-null  object
 2   @lat              50419 non-null  float64
 3   @lon              50419 non-null  float64
 4   @timestamp        50419 non-null  object
 5   name              13383 non-null  object
 6   amenity           19017 non-null  object
 7   shop              2452 non-null   object
 8   healthcare        380 non-null    object
 9   sport             2312 non-null   object
 10  leisure           19766 non-null  object
 11  tourism           1908 non-null   object
 12  office            537 non-null    object
 13  craft             228 non-null    object
 14  public_transport  3513 non-null   object
 15  railway           2595 non-null   object
 16  highway           2079 non-null   object
 17  landuse           23 non-null     object
 18  natural           29 non-null     object
 19  addr:housenumber  1612 non-null   object
 20  addr:street       2017 non-null   object
 21  addr:postcode     1735 non-null   float64
 22  addr:city         1509 non-null   object
 23  operator          4020 non-null   object
 24  brand             1150 non-null   object
 25  phone             2289 non-null   object
 26  website           2148 non-null   object
 27  opening_hours     2768 non-null   object
dtypes: float64(3), int64(1), object(24)
memory usage: 10.8+ MB

 None
total_rows: 50419 total_columns: 28

 @id                     0
@type                   0
@lat                    0
@lon                    0
@timestamp              0
name                37036
amenity             31402
shop                47967
healthcare          50039
sport               48107
leisure             30653
tourism             48511
office              49882
craft               50191
public_transport    46906
railway             47824
highway             48340
landuse             50396
natural             50390
addr:housenumber    48807
addr:street         48402
addr:postcode       48684
addr:city           48910
operator            46399
brand               49269
phone               48130
website             48271
opening_hours       47651
dtype: int64

 Duplicated Any: 0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50419 entries, 0 to 50418
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   @id               50419 non-null  int64
 1   @type             50419 non-null  object
 2   @lat              50419 non-null  float64
 3   @lon              50419 non-null  float64
 4   @timestamp        50419 non-null  object
 5   name              13383 non-null  object
 6   amenity           19017 non-null  object
 7   shop              2452 non-null   object
 8   healthcare        380 non-null    object
 9   sport             2312 non-null   object
 10  leisure           19766 non-null  object
 11  tourism           1908 non-null   object
 12  office            537 non-null    object
 13  craft             228 non-null    object
 14  public_transport  3513 non-null   object
 15  railway           2595 non-null   object
 16  highway           2079 non-null   object
 17  landuse           23 non-null     object
 18  natural           29 non-null     object
 19  addr:housenumber  1612 non-null   object
 20  addr:street       2017 non-null   object
 21  addr:postcode     1735 non-null   float64
 22  addr:city         1509 non-null   object
 23  operator          4020 non-null   object
 24  brand             1150 non-null   object
 25  phone             2289 non-null   object
 26  website           2148 non-null   object
 27  opening_hours     2768 non-null   object
dtypes: float64(3), int64(1), object(24)
memory usage: 10.8+ MB
None

                @id          @lat          @lon  addr:postcode
count  5.041900e+04  50419.000000  50419.000000    1735.000000
mean   3.756914e+09     45.797879      4.738922   69467.640922
std    4.673002e+09      0.177207      0.182725     205.490581
min    1.031209e+06     45.454587      4.239120   69115.000000
25%    1.837864e+08     45.670076      4.640342   69380.000000
50%    1.210854e+09     45.736066      4.716444   69400.000000
75%    6.760434e+09     45.938657      4.824489   69590.000000
max    1.420571e+10     46.301584      5.176216   71570.000000

In [ ]:

# Colonnes NA, type variables, taux
documentation_variables = pd.DataFrame({
    "Valeurs manquantes": df.isnull().sum(),
    "Taux de NA (%)": (df.isna().mean() * 100).round(2).values,
    "Type informatique": df.dtypes.values})

print("\nDocumentation des variables:")
display(documentation_variables)

# Colonne distribution des valeurs
distribution = {}
liste = {}
for col in df.columns:
    if df[col].dtype in ["object", "string", "str"]:

        if df[col].nunique() <= 10:
            distribution[col] = ", ".join(df[col].dropna().astype(str).unique())
            liste[col]= "liste des catégories"
        else:
            distribution[col] = f"{df[col].nunique()} catégories"
            liste[col]= "nbr catégories"

    else:
        
        describe = df[col].describe()
        liste[col]= "Voir statistiques descriptives"
        distribution[col] = (
            f"Min={describe['min']:.2f} | "
            f"Médiane={describe['50%']:.2f} | "
            f"Moyenne={describe['mean']:.2f} | "
            f"Max={describe['max']:.2f}"
        )

documentation_distribution = pd.DataFrame({
    "Nom de la colonne": df.columns,
    "Type": df.dtypes.values,
    "Liste": [liste[col] for col in df.columns],
    "Distribution des valeurs": [distribution[col] for col in df.columns]
})

Documentation des variables :

                  Valeurs manquantes  Taux de NA (%) Type informatique
@id                                0            0.00             int64
@type                              0            0.00            object
@lat                               0            0.00           float64
@lon                               0            0.00           float64
@timestamp                         0            0.00            object
name                           37036           73.46            object
amenity                        31402           62.28            object
shop                           47967           95.14            object
healthcare                     50039           99.25            object
sport                          48107           95.41            object
leisure                        30653           60.80            object
tourism                        48511           96.22            object
office                         49882           98.93            object
craft                          50191           99.55            object
public_transport               46906           93.03            object
railway                        47824           94.85            object
highway                        48340           95.88            object
landuse                        50396           99.95            object
natural                        50390           99.94            object
addr:housenumber               48807           96.80            object
addr:street                    48402           96.00            object
addr:postcode                  48684           96.56           float64
addr:city                      48910           97.01            object
operator                       46399           92.03            object
brand                          49269           97.72            object
phone                          48130           95.46            object
website                        48271           95.74            object
opening_hours                  47651           94.51            object

In [ ]:

#--------------------------------------------------------------
## PRE-PROCESSING  DES DONNÉES OSM
#--------------------------------------------------------------


osm = df.copy()


# Renommage des colonnes techniques
osm = osm.rename(columns={
    "@id": "osm_id",
    "@type": "osm_type",
    "@lat": "latitude",
    "@lon": "longitude",
    "@timestamp": "timestamp"
})


# Conversion des types : Timestamp OSM -> datetime
osm["timestamp"] = pd.to_datetime(osm["timestamp"],
    errors="coerce",
    # utc=True
)

# Coordonnées numériques
osm["latitude"] = pd.to_numeric(osm["latitude"], errors="coerce")
osm["longitude"] = pd.to_numeric(osm["longitude"], errors="coerce")

# ID OSM
osm["osm_id"] = pd.to_numeric(osm["osm_id"], errors="coerce")


# Suppression des colonnes peu utiles pour l'enrichissement
colonnes_a_supprimer = [
    "operator",
    "brand",
    "phone",
    "website",
    "opening_hours"
]

# name conservé pour les contrôles / analyses mais pas utilisé directement comme variable modèle
osm = osm.drop(columns=[c for c in colonnes_a_supprimer if c in osm.columns], errors="ignore")


# Ajout du département pour la traçabilité
osm["code_departement"] = "69"

## 5. Nettoyage des chaînes de caractères
# colonnes_texte = osm.select_dtypes(include="object").columns

# for col in colonnes_texte:
#     osm[col] = osm[col].astype("string").str.strip()


# Contrôle rapide des coordonnées
osm = osm[
    osm["latitude"].between(-90, 90, inclusive="both")
    & osm["longitude"].between(-180, 180, inclusive="both")
].copy()


# Suppression des doublons
osm = osm.drop_duplicates()

#---------------------------------------
## Contrôle final
#---------------------------------------

print("Shape finale :", osm.shape)
print("\nTypes :")
print(osm.dtypes)

print("\nValeurs manquantes :")
print(osm.isna().sum().sort_values(ascending=False).head(15))

print("\nTypes OSM :")
print(osm["osm_type"].value_counts(dropna=False))

osm.head()

osm.to_csv("../data/raw/osm_69_2025_preprocessed.csv",)

print("OSM terminé.")

Shape finale : (50419, 24)

Types :
osm_id                            int64
osm_type                         object
latitude                        float64
longitude                       float64
timestamp           datetime64[ns, UTC]
name                             object
amenity                          object
shop                             object
healthcare                       object
sport                            object
leisure                          object
tourism                          object
office                           object
craft                            object
public_transport                 object
railway                          object
highway                          object
landuse                          object
natural                          object
addr:housenumber                 object
addr:street                      object
addr:postcode                   float64
addr:city                        object
code_departement                 object
dtype: object

Valeurs manquantes :
landuse             50396
natural             50390
craft               50191
healthcare          50039
office              49882
addr:city           48910
addr:housenumber    48807
addr:postcode       48684
tourism             48511
addr:street         48402
highway             48340
sport               48107
shop                47967
railway             47824
public_transport    46906
dtype: int64

Types OSM :
osm_type
way         30443
node        19263
relation      713
Name: count, dtype: int64
OSM terminé.